action_endpoint:
  url: http://action_server:5055/webhook
nlu:
  url: http://rasa_nlu:5000
duckling:
  url: http://duckling:8000  
tracker_store:
  type: mongod
  url: mongodb://mongo:27017
  username: rasa
  password: example      
